---
version: "3.9"
services:
  backend:
    image: wapp-backend
    ports:
      - "9000:9000"
  frontend:
    image: wapp-frontend
    ports:
      - "8000:8000"
    environment:
      ENDPOINT: "https://{{ domain }}/api"
