---
version: "3.9"
services:
  backend:
    build:
      context: ../backend
      tags:
        - wapp-backend
    ports:
      - "9000:9000"
  frontend:
    build:
      context: ../frontend
      tags:
        - wapp-frontend
    ports:
      - "8000:8000"
    environment:
      ENDPOINT: "https://{{ domain }}/api"
