- name: Provision the server
  hosts: gcp

  handlers:
    - name: Reboot the server
      ansible.builtin.reboot:

    - name: Start UFW
      become: true
      ansible.builtin.expect:
        command: ufw enable
        responses:
          "Proceed with operation": y

  tasks:
    - name: General system update
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      notify:
        - Reboot the server

    - name: Neofetch block
      block: # Taken from my install_neofetch role. This is absolutely not necessary, but it wouldn't feel like "my" server without it.
        - name: Ensure git is present
          become: true
          ansible.builtin.apt:
            name: git
            state: present

        - name: Prepare directory for neofetch
          become: true
          ansible.builtin.file:
            path: /opt/neofetch
            state: directory
            mode: 0755

        - name: Get the Neofetch code
          become: true
          ansible.builtin.git:
            dest: /opt/neofetch
            repo: https://github.com/dylanaraps/neofetch.git
            version: "7.1.0"
            force: true

        - name: Copy neofetch script
          become: true
          ansible.builtin.command:
            chdir: /opt/neofetch
            cmd: cp neofetch neofetch-cust
            creates: /opt/neofetch/neofetch-cust

        - name: Patch the 'title' function
          become: true
          ansible.builtin.lineinfile:
            path: /opt/neofetch/neofetch-cust
            search_string: "{{ item.search }}"
            line: "{{ item.line }}"
          loop:
            - {
                search: "    title=${title_color}${bold}${user}",
                line: "    title=${title_color}${bold}${hostname}",
              }
            - {
                search: "length=$((${",
                line: '{% raw %}    length="$((${{ ''{#'' }}hostname}))"{% endraw %}',
              }

        - name: Link Neofetch into /usr/bin
          become: true
          ansible.builtin.file:
            state: link
            path: /usr/bin/neofetch
            src: /opt/neofetch/neofetch-cust

        - name: Enumerate current MOTD scripts
          ansible.builtin.command:
            cmd: ls /etc/update-motd.d
          register: modt_scripts
          changed_when: false

        - name: Disable current motd script
          become: true
          ansible.builtin.file:
            path: "/etc/update-motd.d/{{ item }}"
            mode: 0644
          loop: "{{ modt_scripts.stdout_lines | difference(neofetch_files) }}"

        - name: Check if static MOTD is present
          ansible.builtin.stat:
            path: /etc/motd
          register: static_motd

        - name: Remove static MOTD
          become: true
          ansible.builtin.command:
            cmd: mv /etc/motd /etc/motd.disabled
          when: static_motd.stat.exists

        - name: Install new MOTD script
          become: true
          ansible.builtin.copy:
            src: files/
            dest: /etc/update-motd.d/
            mode: 0755

    - name: Ensure UFW is installed
      become: true
      ansible.builtin.apt:
        name:
          - ufw
        state: present

    - name: Set up UFW rules
      become: true
      ansible.builtin.command:
        cmd: "ufw allow {{ item }}/tcp"
      register: ufw_rules
      changed_when: "'Skipping' not in ufw_rules.stdout"
      loop:
        - 22
        - 80
        - 443
      notify:
        - Start UFW

    - name: Check UFW status
      become: true
      ansible.builtin.command:
        cmd: ufw status
      register: ufw_status
      changed_when: "'Status: inactive' in ufw_status.stdout"
      notify:
        - Start UFW

    - name: Sudo group block
      block: # Adapted from my "ensure_sudo_group" role. Can be used to create user groups allowing either passworded or non-password sudo. In this case, we only want passworded sudo access.
        - name: Check if a sudo group is already defined
          become: true
          ansible.builtin.shell:
            cmd: cat /etc/sudoers | grep ^%sudo
          changed_when: false
          failed_when: false
          register: deb_grep

        - name: Sudo group does not exist
          block:
            - name: Create the group
              become: true
              ansible.builtin.group:
                name: "sudo"
                state: present
                system: true

            - name: Install the sudoers.d file
              become: true
              ansible.builtin.template:
                dest: /etc/sudoers.d/090_ans-sudogroup
                src: templates/sudoers
                mode: 0440
                validate: /usr/sbin/visudo -cf %s
              vars:
                group: "sudo"
          when: not deb_grep.rc == 0

        - name: Register the group name
          ansible.builtin.set_fact:
            sudo_group: "sudo"

    - name: Create a user account for examination purposes
      become: true
      ansible.builtin.user:
        name: "eficode"
        state: present
        password: "$6$CPcj9wyH/kerDPD.$bUP4nHJGKcDJP0le5TOm9vhXMzDFdJW92M381wDMmx7FA0x2obTDAX683Ly61s22ZTGKimXequRt5JTKsEAuB0"
        # I'm aware that a hardcoded password hash like this causes security problems,
        # but in this inscance, I'm willing to accept them. This server isn't intended
        # to be long-lived.

    - name: Grant sudoer rights
      become: true
      ansible.builtin.user:
        name: "eficode"
        append: true
        groups:
          - "{{ sudo_group }}"

    - name: Flush the handlers, ensuring system is ready
      ansible.builtin.meta: flush_handlers
